### ISSUE TITLE
Make it possible to write simple expressions using strings like traditional regular expressions

### ISSUE THREAD

**Issue by pafcu** [pmros/pamatcher#7]
To make it easier to use the library, it would be nice to have an interface that matches more closely that of traditional regular expressions. For more complex expressions the full interface.

E.g. "\int[0-100]" would match integers between 0 and 100, "\int[1,3,5,7]{3,}" would match three or more integers in the set {3,5,7}.

In general, syntax like "[Bar]" could match any element x where x == "Bar" (i.e. use the weak JavaScript equality). (note the difference to normal regular expressions, where this would match either "B", "a" or "r". With this new syntax e.g. a comma would be needed to separate these: "[B,a,r]".

This simplified syntax would not be able to do everything the more complete interface is able to do, but would probably make the most common tasks significantly easier.

**Comment by pmros** [comment]
Thank you very much for your feedback @pafcu. I think your suggestion is a very good idea. I'll try to add this feature as soon as possible.

Thank you again!

**Comment by pmros** [comment]
I've created a wiki page: [Proposal for Pattern Expression Strings (PES)](https://github.com/pmros/pamatcher/wiki/Proposal-for-Pattern-Expression-Strings-(PES)). I think is a notation quite compact and powerful. Feel free to comment this initial specification.

**Comment by pmros** [comment]
pamatcher 0.3.0 is released with [Patter Expression Strings (PES)](https://github.com/pmros/pamatcher/wiki/Pattern-Expression-Strings-%28PES%29) support. I have to update README and website doc.
Please try it and tell me what do you think about.
